#!/bin/bash

# To be installed in /home/nova/bin
# Then a cron job should be created for root to run the script every minute:
# > sudo crontab -e
# * * * * * /home/nova/bin/update-flightdeck-application-server

SERVICE=flightdeck
SERVER_SOURCE=/opt/dsr/repo/latest/flightdeck
SERVER_TARGET=/opt/dsr/web/flightdeck.desertskyrangers.com/server

if [ ! -f $SERVER_SOURCE/publish.flag ]; then
    exit 0;
fi

echo "Deploying server: $SERVER_SOURCE/server.jar"
echo "              To: $SERVER_TARGET/$SERVICE.jar"
echo ""
echo "To enable:  sudo systemctl enable $SERVER_TARGET/$SERVICE.service"
echo "To disable: sudo systemctl disable $SERVICE"

cp $SERVER_SOURCE/server.jar $SERVER_TARGET/$SERVICE.jar
cp $SERVER_SOURCE/$SERVICE.service $SERVER_TARGET/$SERVICE.service
cp $SERVER_SOURCE/application.yml $SERVER_TARGET/application.yml
cp $SERVER_SOURCE/$SERVICE.conf $SERVER_TARGET/$SERVICE.conf
rm $SERVER_SOURCE/publish.flag

chown nova:nova $SERVER_TARGET/*

systemctl daemon-reload
systemctl restart $SERVICE.service
